CREATE TABLE IF NOT EXISTS fact_analytics (
  sku_ms text PRIMARY KEY REFERENCES dim_sku(sku_ms) ON DELETE CASCADE,
  upload_id uuid REFERENCES uploads(id),
  uploaded_at timestamptz DEFAULT now(),
  -- identity
  name text,
  sku_wb bigint,
  brand text,
  category text,
  -- metadata
  cost_updated_at date,
  status text,
  comment text,
  supplier text,
  country text,
  currency text,
  -- pricing & economics
  target_margin numeric,
  rating numeric,
  reviews_count int,
  reviews_last10 text,
  commission_offer_fbo numeric,
  abc_month text,
  abc_daily text,
  available_wb boolean,
  stock_fbo int,
  stock_fbs int,
  avg_daily_sales numeric,
  volume_storage numeric,
  cost_price numeric,
  base_logistics numeric,
  volume_l numeric,
  buyout_pct numeric,
  profit_correction numeric,
  commission_fbo numeric,
  commission_fbs numeric,
  defect_pct numeric,
  base_price numeric,
  set_discount_pct numeric,
  price_wb numeric,
  spp numeric,
  price_with_spp numeric,
  rrp numeric,
  promo text,
  calc_margin numeric,
  promo_active boolean,
  -- 7 promo blocks (35 columns: price, margin_drop, penalty, profit, margin per block)
  promo_price_1 numeric, margin_drop_1 numeric, penalty_1 numeric, promo_profit_1 numeric, promo_margin_1 numeric,
  promo_price_2 numeric, margin_drop_2 numeric, penalty_2 numeric, promo_profit_2 numeric, promo_margin_2 numeric,
  promo_price_3 numeric, margin_drop_3 numeric, penalty_3 numeric, promo_profit_3 numeric, promo_margin_3 numeric,
  promo_price_4 numeric, margin_drop_4 numeric, penalty_4 numeric, promo_profit_4 numeric, promo_margin_4 numeric,
  promo_price_5 numeric, margin_drop_5 numeric, penalty_5 numeric, promo_profit_5 numeric, promo_margin_5 numeric,
  promo_price_6 numeric, margin_drop_6 numeric, penalty_6 numeric, promo_profit_6 numeric, promo_margin_6 numeric,
  promo_price_7 numeric, margin_drop_7 numeric, penalty_7 numeric, promo_profit_7 numeric, promo_margin_7 numeric,
  -- final calculations
  desired_margin_fbs numeric,
  new_price numeric,
  new_margin numeric,
  promo_now boolean,
  new_discount numeric,
  exact_discounted_price numeric,
  new_base numeric,
  price_change numeric,
  offer_margin numeric
);

CREATE INDEX IF NOT EXISTS idx_fact_analytics_sku_wb ON fact_analytics(sku_wb);
CREATE INDEX IF NOT EXISTS idx_fact_analytics_upload ON fact_analytics(upload_id);
